<?php
namespace ClusterPoint;

/**
* Cluster Point Database
* @author Faizan Ayubi
*/
class DB {
	
	const ACCOUNT_ID = 'account-id';
    const DATABASE = 'db';
    const AUTH = 'user@domain.com:pass';

	public function url() {
		$url = 'https://api-eu.clusterpoint.com/v4/' . self::ACCOUNT_ID . '/' . self::DATABASE;
		return $url;
	}

	public function create($doc) {
		$ch = curl_init();
		// https://api-eu.clusterpoint.com/v4/ACCOUNT_ID/DATABASE_NAME[ID]     -  Insert single document with explicit ID
		curl_setopt($ch, CURLOPT_URL, $this->url()); //  In this case document ID is automatically generated by system.
		curl_setopt($ch, CURLOPT_USERPWD, self::AUTH);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($doc));
		$response = curl_exec($ch);
		$errorMsg = curl_error($ch);
		if ($errorMsg) {
			var_dump($errorMsg);
		}
		curl_close($ch);
	}

	public function update($id, $click) {
		$query = 'UPDATE stats["' . $id . '"] SET hit = "' . $click . '"';
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $this->url() . '/_query');
		curl_setopt($ch, CURLOPT_USERPWD, self::AUTH);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST"); // or use PATCH request  https://www.clusterpoint.com/docs/?page=Update
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
		$response = curl_exec($ch);
		$errorMsg = curl_error($ch);
		if ($errorMsg) {
			var_dump($errorMsg);
		}
		curl_close($ch);
	}

	public function delete($id) {
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $this->url() . '['.$id.']');
		curl_setopt($ch, CURLOPT_USERPWD, self::AUTH);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		$response = curl_exec($ch);
		$errorMsg = curl_error($ch);
		if ($errorMsg) {
			var_dump($errorMsg);
		}
		curl_close($ch);
	}

	public function read($item) {
		$query = "SELECT * FROM stats WHERE trigger_id == ".$item["trigger_id"]." && user_id == ".$item["user_id"]." LIMIT 1";
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $this->url() . '/_query'); // We added _query here!
		curl_setopt($ch, CURLOPT_USERPWD, self::AUTH);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
		$response = json_decode(curl_exec($ch));
		curl_close($ch);
		return isset($response->results) ? $response->results : NULL;
	}

	public function index($query='') {
		$ch = curl_init();
		
		curl_setopt($ch, CURLOPT_URL, $this->url() . '/_query'); // We added _query here!
		curl_setopt($ch, CURLOPT_USERPWD, self::AUTH);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
		$response = json_decode(curl_exec($ch));
		$errorMsg = curl_error($ch);
		if ($errorMsg) {
			var_dump($errorMsg);
		}
		curl_close($ch);

		return $response->results;
	}

}
